development: &default
  adapter: postgresql
  database: bandjob_development

test: &test
  <<: *default
  database: bandjob_test


cucumber:
  <<: *test

production:
  <<: *default
  database: bandjob_production
